version: '3.8'
services:
  app:
    image: 'lexware-demo-meldecenter:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo_db
      - SPRING_DATASOURCE_USERNAME=demo_user
      - SPRING_DATASOURCE_PASSWORD=demo_pass
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
